# Generated by Django 2.0.6 on 2018-07-01 10:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0009_alter_user_last_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('abreviation', models.CharField(default='GOOG', max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Portfolio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assetClass', models.CharField(max_length=200)),
                ('tarjet', models.IntegerField(default=0)),
                ('marketValue', models.IntegerField(default=0)),
                ('returned', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='PredictionList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dateStock', models.CharField(max_length=10)),
                ('estimate', models.FloatField(default=0)),
                ('change', models.FloatField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dateStock', models.CharField(max_length=10)),
                ('close', models.FloatField(default=1)),
                ('volume', models.IntegerField(default=1)),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('amount', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('userid', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('username', models.CharField(max_length=200)),
                ('password', models.CharField(max_length=200)),
                ('email', models.CharField(max_length=200)),
                ('age', models.IntegerField(default=18)),
                ('initialInvestment', models.IntegerField(default=0)),
                ('timeInvest', models.IntegerField(default=0)),
                ('risklevel', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='UserProjection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('investment', models.IntegerField(default=18)),
                ('userid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='robadv.UserProfile')),
            ],
        ),
        migrations.CreateModel(
            name='Prediction',
            fields=[
                ('company', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='robadv.Company')),
                ('day', models.IntegerField(default=0)),
                ('nshares', models.IntegerField(default=0)),
            ],
        ),
        migrations.AddField(
            model_name='transaction',
            name='userid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='robadv.UserProfile'),
        ),
        migrations.AddField(
            model_name='stock',
            name='companyFK',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='robadv.Company'),
        ),
        migrations.AddField(
            model_name='portfolio',
            name='userid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='robadv.UserProfile'),
        ),
        migrations.AddField(
            model_name='predictionlist',
            name='predictionFK',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='robadv.Prediction'),
        ),
    ]
