# Generated by Django 2.0.6 on 2018-07-01 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('robadv', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='initialInvestment',
            field=models.BigIntegerField(default=0),
        ),
    ]
