# Generated by Django 2.0.6 on 2018-07-04 15:14

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('robadv', '0006_portfolio_assetid'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='category',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='portfolio',
            name='description',
            field=models.CharField(default=django.utils.timezone.now, max_length=1000),
            preserve_default=False,
        ),
    ]
