# Generated by Django 2.0.6 on 2018-07-04 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('robadv', '0008_auto_20180704_1723'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='change',
            field=models.FloatField(default=0),
        ),
    ]
