# Generated by Django 2.0.6 on 2018-07-10 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('robadv', '0009_auto_20180704_1926'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='shares',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='company',
            name='price',
            field=models.FloatField(default=0),
        ),
    ]
