# Generated by Django 2.0.6 on 2018-07-11 17:08

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('robadv', '0010_auto_20180710_2152'),
    ]

    operations = [
        migrations.AddField(
            model_name='portfolio',
            name='lastUpdate',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
