# Generated by Django 2.0.6 on 2018-07-11 17:14

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('robadv', '0011_portfolio_lastupdate'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='portfolio',
            name='lastUpdate',
        ),
        migrations.AddField(
            model_name='company',
            name='lastUpdate',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
