# Generated by Django 2.0.6 on 2018-07-13 16:44

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('robadv', '0014_auto_20180713_1742'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='portfolio',
            name='creationDate',
        ),
        migrations.RemoveField(
            model_name='portfolio',
            name='lastUpdate',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='creationDate',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='lastUpdate',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
