# Generated by Django 2.0.6 on 2018-07-15 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('robadv', '0015_auto_20180713_1744'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='companyFK',
            field=models.ManyToManyField(blank=True, to='robadv.Company'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='accountAge',
            field=models.IntegerField(default=1),
        ),
    ]
