# Generated by Django 2.0.6 on 2018-07-15 21:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('robadv', '0016_auto_20180715_2112'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='userid',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='robadv.UserProfile'),
        ),
    ]
