# Generated by Django 2.0.6 on 2018-07-16 00:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('robadv', '0017_company_userid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='company',
            name='userid',
        ),
    ]
