# Generated by Django 2.0.6 on 2018-07-16 15:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('robadv', '0018_remove_company_userid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction',
            name='companyFK',
        ),
        migrations.AddField(
            model_name='transaction',
            name='companyFK',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='robadv.Company'),
            preserve_default=False,
        ),
    ]
