# Generated by Django 2.0.6 on 2018-07-19 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('robadv', '0020_auto_20180716_1649'),
    ]

    operations = [
        migrations.AlterField(
            model_name='portfolio',
            name='returned',
            field=models.FloatField(default=0),
        ),
    ]
