# Generated by Django 2.0.6 on 2018-07-19 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('robadv', '0021_auto_20180719_1443'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprojection',
            name='nmonth',
            field=models.IntegerField(default=0),
        ),
    ]
